services:
  - type: web
    name: webtermux
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: webtermux
          property: port
    healthCheckPath: /
    numInstances: 1
    region: oregon